import "primereact/resources/themes/lara-light-indigo/theme.css"; //theme
import "primereact/resources/primereact.min.css"; //core css
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import { BrowserRouter as Router, Route, Switch } from "react-router-dom";
import Links from "./components/Links";

import Navbar from "./components/Navbar";
import Hero from "./components/Hero";
import Footer from "./components/Footer";
import Features from "./components/features";
// import Head from "next/head";

function App() {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Navbar />
      <main>
        <Hero />
        <Features />
      </main>
      <Footer />
    </div>
    // <Router>
    //   <Switch>
    //     <Navbar />

    //     <main>
    //       <Hero />
    //       <Features />
    //     </main>

    //     <Footer />
    //     <Route path="/:username">
    //       <div className="p-m-4">
    //         <Links />
    //       </div>
    //     </Route>
    //   </Switch>
    // </Router>
  );
}

export default App;
